mv relayer from https://github.com/sora-xor/sora2-network/commit/5737…
sora-xor/bridge-relayer pull request #1
Opened 2023-10-18 13:49 UTC by Alexey-N-Chernyshov

…0c3bde1b29e5dc5862f75dba79d1a0b5f57c

2023-10-26 05:51 UTC, wpi86 requested changes

2023-10-26 05:51 UTC, wpi86 commented on .github/workflows/static_analysis.yml
> +      - uses: actions/checkout@v4
pin versions with hash on all steps

2023-10-26 06:13 UTC, Alexey-N-Chernyshov commented on .github/workflows/static_analysis.yml
> +      - uses: actions/checkout@v4
done

2023-10-27 05:58 UTC, wpi86 approved these changes

2023-10-30 10:07 UTC, vovac12 approved these changes

2023-10-30 10:33 UTC, merged